[nuitron]
git.url = "https://github.com/rayanamal/nuitron.git"
git.commit = "ca7ec24a"
dev.path = '~/nuitron/mod.nu'

[depman-v001]
git.url = "https://github.com/depman-org/depman.git"
git.commit = "dcc0bae0"
